name: SonarCloud
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # necesar pentru rapoartele de blame

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'   # JDK pentru build/scan

      - name: Build (opțional poți sări testele)
        run: mvn -B -DskipTests package

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
